// -*- mode: json -*-
{
	"layer": "top",
	"position": "top",

	"modules-left": [
		"hyprland/workspaces",
		"tray",
		"custom/right-arrow-dark"
	],
	"modules-center": [
		"custom/left-arrow-dark",
		"clock#1",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"clock#2",
		"custom/right-arrow-dark",
		"custom/right-arrow-light",
		"clock#3",
		"custom/right-arrow-dark"
	],
	"modules-right": [
		"custom/left-arrow-dark",
		"hyprland/language",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"backlight",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"pulseaudio",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"memory",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"cpu",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"temperature",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"battery",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"network",
	],

	"custom/left-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-light": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-light": {
		"format": "",
		"tooltip": false
	},

	"sway/workspaces": {
		"disable-scroll": true,
		"format": "{name}"
	},

	"clock#1": {
		"format": "{:%a}",
		"tooltip": false
	},
	"clock#2": {
		"format": "{:%H:%M}",
		"tooltip": false
	},
	"clock#3": {
		"format": "{:%d-%m}",
		"tooltip": false
	},

	"pulseaudio": {
		"format": "{icon}  {volume:2}%",
		"format-bluetooth": "{icon} {volume}%",
		"format-muted": "{MUTE",
		"format-icons": {
			"headphones": "",
			"default": [
				"","","","","",
			]
		},
		"scroll-step": 5,
		"on-click": "pamixer -t",
		"on-click-right": "pavucontrol"
	},
	"memory": {
		"interval": 5,
		"format": "{icon} {}%",
		"format-icons": [
			""
		]
	},
	"cpu": {
		"interval": 5,
		"format": "{icon} {usage:2}%",
		"format-icons": [
			""
		]
	},
	"battery": {
		"states": {
			"good": 95,
			"warning": 30,
			"critical": 15
		},
		"format": "{icon}  {capacity}%",
		"format-icons": [
			"","","","",""
		]
	},
	"temperature": {
        // "thermal-zone": 2,
        // "hwmon-path": "/sys/class/hwmon/hwmon2/temp1_input",
        "critical-threshold": 80,
        // "format-critical": "{temperatureC}°C {icon}",
        "format": "{icon} {temperatureC}°C",
        "format-icons": ["", "", ""]
    },
		"backlight": {
        // "device": "acpi_video1",
        "format": "{icon} {percent}%",
        "format-icons": ["󰃞", "󰃝", "󰃟", "󰃠"]
    },
		"hyprland/language": {
				"format": "  {}",
				"format-en": "US",
				"format-ru": "RU",
				"format-ua": "UA",
				"format-tr": "As bayrakları",
				"keyboard-name": "at-translated-set-2-keyboard"
		},
		"network": {
      "interval": 5,
      "format-wifi": " 󰖩  {essid} ", // Icon: wifi
      "format-ethernet": "  {ifname}: {ipaddr}/{cidr}", // Icon: ethernet
			"format-disconnected": " 󰖪  Disconnected ",
      "tooltip-format": "{ifname}: {ipaddr}"
    },
	"tray": {
		"icon-size": 20
	}
}
